import { MockService } from "../app/types/invoiceTypes";

export const MOCK_SERVICES: MockService[] = [
  {
    id: "srv-1",
    name: "Initial Consultation",
    description: "Comprehensive first-time patient consultation and assessment",
    duration: 60,
    price: 150,
    category: "Consultation",
    isActive: true,
  },
  {
    id: "srv-2",
    name: "Follow-up Visit",
    description: "Regular follow-up appointment for existing patients",
    duration: 30,
    price: 75,
    category: "Consultation",
    isActive: true,
  },
  {
    id: "srv-3",
    name: "Dental Cleaning",
    description: "Professional teeth cleaning and oral hygiene maintenance",
    duration: 45,
    price: 120,
    category: "Dental",
    isActive: true,
  },
  {
    id: "srv-4",
    name: "X-Ray Imaging",
    description: "Digital radiographic imaging for diagnostic purposes",
    duration: 20,
    price: 80,
    category: "Diagnostic",
    isActive: true,
  },
  {
    id: "srv-5",
    name: "Physiotherapy Session",
    description: "Targeted physical rehab and muscle strength assessment",
    duration: 45,
    price: 110,
    category: "Therapy",
    isActive: true,
  },
  {
    id: "srv-6",
    name: "Blood Test & Lab Panel",
    description: "Full blood count and metabolic diagnostic screening",
    duration: 15,
    price: 95,
    category: "Diagnostic",
    isActive: true,
  },
];
