import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type ThemePalette =
  | "light"
  | "dark-core"
  | "soft-pastel"
  | "high-contrast"
  | "indigo-pulse"
  | "sales-ignite"
  | "growth-analytics"
  | "enterprise-slate"
  | "realty-premium"
  | "urban-blue"
  | "ai-neon";

interface ThemeContextType {
  theme: ThemePalette;
  setTheme: (theme: ThemePalette) => void;
  accentColor: string;
  setAccentColor: (color: string) => void;
}

const ThemeContext = createContext<ThemeContextType | undefined>(undefined);

const themes = {
  "dark-core": {
    "--bg-app": "#0F172A",
    "--bg-sidebar": "#111827",
    "--bg-surface": "#1E293B",
    "--bg-surface-alt": "#273449",
    "--bg-modal": "#1E293B",
    "--bg-dropdown": "#1E293B",
    "--text-primary": "#F8FAFC",
    "--text-secondary": "#CBD5E1",
    "--text-muted": "#94A3B8",
    "--text-inverse": "#0F172A",
    "--border-default": "#334155",
    "--border-strong": "#475569",
    "--accent-primary": "#3B82F6",
    "--accent-secondary": "#10B981",
    "--accent-soft": "#1E3A5F",
    "--accent-hover": "#60A5FA",
    "--accent-active": "#2563EB",
    "--status-success": "#10B981",
    "--status-warning": "#F59E0B",
    "--status-error": "#EF4444",
    "--status-info": "#3B82F6",
    "--chart-primary": "#3B82F6",
    "--chart-secondary": "#10B981",
    "--chart-success": "#10B981",
    "--chart-error": "#EF4444",
    "--chart-warning": "#F59E0B",
    "--chart-grid": "#334155",
    "--chart-axis": "#94A3B8",
    "--sidebar-bg": "#111827",
    "--sidebar-text": "#F8FAFC",
    "--sidebar-text-muted": "#94A3B8",
    "--sidebar-icon": "#94A3B8",
    "--sidebar-icon-active": "#3B82F6",
    "--sidebar-item-hover-bg": "#1E293B",
    "--sidebar-item-active-bg": "#1E3A5F",
    "--sidebar-item-active-text": "#60A5FA",
    "--sidebar-border": "#334155",
    "--sidebar-profile-bg": "#0F172A",
  },
  light: {
    "--bg-app": "#F8FAFC",
    "--bg-sidebar": "#FFFFFF",
    "--bg-surface": "#FFFFFF",
    "--bg-surface-alt": "#F1F5F9",
    "--bg-modal": "#FFFFFF",
    "--bg-dropdown": "#FFFFFF",
    "--text-primary": "#0F172A",
    "--text-secondary": "#475569",
    "--text-muted": "#94A3B8",
    "--text-inverse": "#FFFFFF",
    "--border-default": "#E2E8F0",
    "--border-strong": "#CBD5E1",
    "--accent-primary": "#2563EB",
    "--accent-secondary": "#10B981",
    "--accent-soft": "#DBEAFE",
    "--accent-hover": "#1D4ED8",
    "--accent-active": "#1E40AF",
    "--status-success": "#10B981",
    "--status-warning": "#F59E0B",
    "--status-error": "#DC2626",
    "--status-info": "#2563EB",
    "--chart-primary": "#2563EB",
    "--chart-secondary": "#10B981",
    "--chart-success": "#10B981",
    "--chart-error": "#DC2626",
    "--chart-warning": "#F59E0B",
    "--chart-grid": "#E2E8F0",
    "--chart-axis": "#64748B",
    "--sidebar-bg": "#FFFFFF",
    "--sidebar-text": "#0F172A",
    "--sidebar-text-muted": "#64748B",
    "--sidebar-icon": "#64748B",
    "--sidebar-icon-active": "#2563EB",
    "--sidebar-item-hover-bg": "#F1F5F9",
    "--sidebar-item-active-bg": "#DBEAFE",
    "--sidebar-item-active-text": "#1D4ED8",
    "--sidebar-border": "#E2E8F0",
    "--sidebar-profile-bg": "#F8FAFC",
  },
  "soft-pastel": {
    "--bg-app": "#FFF7ED",
    "--bg-sidebar": "#FFF1F2",
    "--bg-surface": "#FFFFFF",
    "--bg-surface-alt": "#FEF3C7",
    "--bg-modal": "#FFFFFF",
    "--bg-dropdown": "#FFFFFF",
    "--text-primary": "#3B2F2F",
    "--text-secondary": "#7C5C5C",
    "--text-muted": "#A78B8B",
    "--text-inverse": "#FFFFFF",
    "--border-default": "#FAD7C5",
    "--border-strong": "#F4C2A8",
    "--accent-primary": "#EC4899",
    "--accent-secondary": "#F59E0B",
    "--accent-soft": "#FCE7F3",
    "--accent-hover": "#DB2777",
    "--accent-active": "#BE185D",
    "--status-success": "#10B981",
    "--status-warning": "#F59E0B",
    "--status-error": "#DC2626",
    "--status-info": "#EC4899",
    "--chart-primary": "#EC4899",
    "--chart-secondary": "#F59E0B",
    "--chart-success": "#10B981",
    "--chart-error": "#DC2626",
    "--chart-warning": "#F59E0B",
    "--chart-grid": "#FAD7C5",
    "--chart-axis": "#A78B8B",
    "--sidebar-bg": "#FFF1F2",
    "--sidebar-text": "#3B2F2F",
    "--sidebar-text-muted": "#A78B8B",
    "--sidebar-icon": "#A78B8B",
    "--sidebar-icon-active": "#EC4899",
    "--sidebar-item-hover-bg": "#FCE7F3",
    "--sidebar-item-active-bg": "#FCE7F3",
    "--sidebar-item-active-text": "#DB2777",
    "--sidebar-border": "#FAD7C5",
    "--sidebar-profile-bg": "#FFF7ED",
  },
  "high-contrast": {
    "--bg-app": "#000000",
    "--bg-sidebar": "#0A0A0A",
    "--bg-surface": "#111111",
    "--bg-surface-alt": "#1A1A1A",
    "--bg-modal": "#111111",
    "--bg-dropdown": "#111111",
    "--text-primary": "#FFFFFF",
    "--text-secondary": "#E5E7EB",
    "--text-muted": "#A3A3A3",
    "--text-inverse": "#000000",
    "--border-default": "#404040",
    "--border-strong": "#606060",
    "--accent-primary": "#FACC15",
    "--accent-secondary": "#22D3EE",
    "--accent-soft": "#3A3000",
    "--accent-hover": "#FDE047",
    "--accent-active": "#EAB308",
    "--status-success": "#22C55E",
    "--status-warning": "#FACC15",
    "--status-error": "#EF4444",
    "--status-info": "#22D3EE",
    "--chart-primary": "#FACC15",
    "--chart-secondary": "#22D3EE",
    "--chart-success": "#22C55E",
    "--chart-error": "#EF4444",
    "--chart-warning": "#FACC15",
    "--chart-grid": "#404040",
    "--chart-axis": "#A3A3A3",
    "--sidebar-bg": "#0A0A0A",
    "--sidebar-text": "#FFFFFF",
    "--sidebar-text-muted": "#A3A3A3",
    "--sidebar-icon": "#A3A3A3",
    "--sidebar-icon-active": "#FACC15",
    "--sidebar-item-hover-bg": "#1A1A1A",
    "--sidebar-item-active-bg": "#3A3000",
    "--sidebar-item-active-text": "#FDE047",
    "--sidebar-border": "#404040",
    "--sidebar-profile-bg": "#000000",
  },
  "indigo-pulse": {
    "--bg-app": "#0F172A",
    "--bg-sidebar": "#111827",
    "--bg-surface": "#1E293B",
    "--bg-surface-alt": "#273449",
    "--bg-modal": "#1E293B",
    "--bg-dropdown": "#1E293B",
    "--text-primary": "#EEF2FF",
    "--text-secondary": "#C7D2FE",
    "--text-muted": "#818CF8",
    "--text-inverse": "#0F172A",
    "--border-default": "#3730A3",
    "--border-strong": "#4338CA",
    "--accent-primary": "#6366F1",
    "--accent-secondary": "#818CF8",
    "--accent-soft": "#312E81",
    "--accent-hover": "#818CF8",
    "--accent-active": "#4F46E5",
    "--status-success": "#10B981",
    "--status-warning": "#F59E0B",
    "--status-error": "#EF4444",
    "--status-info": "#6366F1",
    "--chart-primary": "#6366F1",
    "--chart-secondary": "#818CF8",
    "--chart-success": "#10B981",
    "--chart-error": "#EF4444",
    "--chart-warning": "#F59E0B",
    "--chart-grid": "#3730A3",
    "--chart-axis": "#818CF8",
    "--sidebar-bg": "#111827",
    "--sidebar-text": "#EEF2FF",
    "--sidebar-text-muted": "#818CF8",
    "--sidebar-icon": "#818CF8",
    "--sidebar-icon-active": "#6366F1",
    "--sidebar-item-hover-bg": "#1E293B",
    "--sidebar-item-active-bg": "#312E81",
    "--sidebar-item-active-text": "#818CF8",
    "--sidebar-border": "#3730A3",
    "--sidebar-profile-bg": "#0F172A",
  },
  "sales-ignite": {
    "--bg-app": "#1C1917",
    "--bg-sidebar": "#211A16",
    "--bg-surface": "#292524",
    "--bg-surface-alt": "#3A2A20",
    "--bg-modal": "#292524",
    "--bg-dropdown": "#292524",
    "--text-primary": "#FFF7ED",
    "--text-secondary": "#FDBA74",
    "--text-muted": "#A8A29E",
    "--text-inverse": "#1C1917",
    "--border-default": "#7C2D12",
    "--border-strong": "#9A3412",
    "--accent-primary": "#F97316",
    "--accent-secondary": "#FB923C",
    "--accent-soft": "#431407",
    "--accent-hover": "#FB923C",
    "--accent-active": "#EA580C",
    "--status-success": "#10B981",
    "--status-warning": "#FBBF24",
    "--status-error": "#EF4444",
    "--status-info": "#F97316",
    "--chart-primary": "#F97316",
    "--chart-secondary": "#FB923C",
    "--chart-success": "#10B981",
    "--chart-error": "#EF4444",
    "--chart-warning": "#FBBF24",
    "--chart-grid": "#7C2D12",
    "--chart-axis": "#A8A29E",
    "--sidebar-bg": "#211A16",
    "--sidebar-text": "#FFF7ED",
    "--sidebar-text-muted": "#A8A29E",
    "--sidebar-icon": "#A8A29E",
    "--sidebar-icon-active": "#F97316",
    "--sidebar-item-hover-bg": "#292524",
    "--sidebar-item-active-bg": "#431407",
    "--sidebar-item-active-text": "#FB923C",
    "--sidebar-border": "#7C2D12",
    "--sidebar-profile-bg": "#1C1917",
  },
  "growth-analytics": {
    "--bg-app": "#102014",
    "--bg-sidebar": "#12251A",
    "--bg-surface": "#1A2E22",
    "--bg-surface-alt": "#223A2A",
    "--bg-modal": "#1A2E22",
    "--bg-dropdown": "#1A2E22",
    "--text-primary": "#F0FDF4",
    "--text-secondary": "#BBF7D0",
    "--text-muted": "#86EFAC",
    "--text-inverse": "#102014",
    "--border-default": "#166534",
    "--border-strong": "#15803D",
    "--accent-primary": "#22C55E",
    "--accent-secondary": "#FACC15",
    "--accent-soft": "#14532D",
    "--accent-hover": "#4ADE80",
    "--accent-active": "#16A34A",
    "--status-success": "#22C55E",
    "--status-warning": "#FACC15",
    "--status-error": "#EF4444",
    "--status-info": "#22C55E",
    "--chart-primary": "#22C55E",
    "--chart-secondary": "#FACC15",
    "--chart-success": "#22C55E",
    "--chart-error": "#EF4444",
    "--chart-warning": "#FACC15",
    "--chart-grid": "#166534",
    "--chart-axis": "#86EFAC",
    "--sidebar-bg": "#12251A",
    "--sidebar-text": "#F0FDF4",
    "--sidebar-text-muted": "#86EFAC",
    "--sidebar-icon": "#86EFAC",
    "--sidebar-icon-active": "#22C55E",
    "--sidebar-item-hover-bg": "#1A2E22",
    "--sidebar-item-active-bg": "#14532D",
    "--sidebar-item-active-text": "#4ADE80",
    "--sidebar-border": "#166534",
    "--sidebar-profile-bg": "#102014",
  },
  "enterprise-slate": {
    "--bg-app": "#111827",
    "--bg-sidebar": "#0F172A",
    "--bg-surface": "#1F2937",
    "--bg-surface-alt": "#273549",
    "--bg-modal": "#1F2937",
    "--bg-dropdown": "#1F2937",
    "--text-primary": "#F9FAFB",
    "--text-secondary": "#CBD5E1",
    "--text-muted": "#94A3B8",
    "--text-inverse": "#111827",
    "--border-default": "#475569",
    "--border-strong": "#64748B",
    "--accent-primary": "#38BDF8",
    "--accent-secondary": "#0EA5E9",
    "--accent-soft": "#082F49",
    "--accent-hover": "#7DD3FC",
    "--accent-active": "#0EA5E9",
    "--status-success": "#10B981",
    "--status-warning": "#F59E0B",
    "--status-error": "#DC2626",
    "--status-info": "#38BDF8",
    "--chart-primary": "#38BDF8",
    "--chart-secondary": "#0EA5E9",
    "--chart-success": "#10B981",
    "--chart-error": "#DC2626",
    "--chart-warning": "#F59E0B",
    "--chart-grid": "#475569",
    "--chart-axis": "#94A3B8",
    "--sidebar-bg": "#0F172A",
    "--sidebar-text": "#F9FAFB",
    "--sidebar-text-muted": "#94A3B8",
    "--sidebar-icon": "#94A3B8",
    "--sidebar-icon-active": "#38BDF8",
    "--sidebar-item-hover-bg": "#1F2937",
    "--sidebar-item-active-bg": "#082F49",
    "--sidebar-item-active-text": "#7DD3FC",
    "--sidebar-border": "#475569",
    "--sidebar-profile-bg": "#111827",
  },
  "realty-premium": {
    "--bg-app": "#0F1F1A",
    "--bg-sidebar": "#10251D",
    "--bg-surface": "#18352A",
    "--bg-surface-alt": "#214536",
    "--bg-modal": "#18352A",
    "--bg-dropdown": "#18352A",
    "--text-primary": "#FFF7ED",
    "--text-secondary": "#D6B56D",
    "--text-muted": "#A3A38A",
    "--text-inverse": "#0F1F1A",
    "--border-default": "#5A4A24",
    "--border-strong": "#6B5A35",
    "--accent-primary": "#D4AF37",
    "--accent-secondary": "#B8941A",
    "--accent-soft": "#3B3218",
    "--accent-hover": "#EACB66",
    "--accent-active": "#B8941A",
    "--status-success": "#16A34A",
    "--status-warning": "#FACC15",
    "--status-error": "#DC2626",
    "--status-info": "#D4AF37",
    "--chart-primary": "#D4AF37",
    "--chart-secondary": "#B8941A",
    "--chart-success": "#16A34A",
    "--chart-error": "#DC2626",
    "--chart-warning": "#FACC15",
    "--chart-grid": "#5A4A24",
    "--chart-axis": "#A3A38A",
    "--sidebar-bg": "#10251D",
    "--sidebar-text": "#FFF7ED",
    "--sidebar-text-muted": "#A3A38A",
    "--sidebar-icon": "#A3A38A",
    "--sidebar-icon-active": "#D4AF37",
    "--sidebar-item-hover-bg": "#18352A",
    "--sidebar-item-active-bg": "#3B3218",
    "--sidebar-item-active-text": "#EACB66",
    "--sidebar-border": "#5A4A24",
    "--sidebar-profile-bg": "#0F1F1A",
  },
  "urban-blue": {
    "--bg-app": "#0F172A",
    "--bg-sidebar": "#102033",
    "--bg-surface": "#1E3A5F",
    "--bg-surface-alt": "#24476F",
    "--bg-modal": "#1E3A5F",
    "--bg-dropdown": "#1E3A5F",
    "--text-primary": "#F8FAFC",
    "--text-secondary": "#BFDBFE",
    "--text-muted": "#93C5FD",
    "--text-inverse": "#0F172A",
    "--border-default": "#2563EB",
    "--border-strong": "#3B82F6",
    "--accent-primary": "#0EA5E9",
    "--accent-secondary": "#38BDF8",
    "--accent-soft": "#075985",
    "--accent-hover": "#38BDF8",
    "--accent-active": "#0284C7",
    "--status-success": "#10B981",
    "--status-warning": "#F59E0B",
    "--status-error": "#DC2626",
    "--status-info": "#0EA5E9",
    "--chart-primary": "#0EA5E9",
    "--chart-secondary": "#38BDF8",
    "--chart-success": "#10B981",
    "--chart-error": "#DC2626",
    "--chart-warning": "#F59E0B",
    "--chart-grid": "#2563EB",
    "--chart-axis": "#93C5FD",
    "--sidebar-bg": "#102033",
    "--sidebar-text": "#F8FAFC",
    "--sidebar-text-muted": "#93C5FD",
    "--sidebar-icon": "#93C5FD",
    "--sidebar-icon-active": "#0EA5E9",
    "--sidebar-item-hover-bg": "#1E3A5F",
    "--sidebar-item-active-bg": "#075985",
    "--sidebar-item-active-text": "#38BDF8",
    "--sidebar-border": "#2563EB",
    "--sidebar-profile-bg": "#0F172A",
  },
  "ai-neon": {
    "--bg-app": "#080A1A",
    "--bg-sidebar": "#0D1025",
    "--bg-surface": "#111633",
    "--bg-surface-alt": "#171D40",
    "--bg-modal": "#111633",
    "--bg-dropdown": "#111633",
    "--text-primary": "#F8FAFC",
    "--text-secondary": "#C4B5FD",
    "--text-muted": "#8B5CF6",
    "--text-inverse": "#080A1A",
    "--border-default": "#4C1D95",
    "--border-strong": "#5B21B6",
    "--accent-primary": "#A855F7",
    "--accent-secondary": "#22D3EE",
    "--accent-soft": "#2E1065",
    "--accent-hover": "#C084FC",
    "--accent-active": "#9333EA",
    "--status-success": "#10B981",
    "--status-warning": "#F59E0B",
    "--status-error": "#F43F5E",
    "--status-info": "#A855F7",
    "--chart-primary": "#A855F7",
    "--chart-secondary": "#22D3EE",
    "--chart-success": "#10B981",
    "--chart-error": "#F43F5E",
    "--chart-warning": "#F59E0B",
    "--chart-grid": "#4C1D95",
    "--chart-axis": "#8B5CF6",
    "--sidebar-bg": "#0D1025",
    "--sidebar-text": "#F8FAFC",
    "--sidebar-text-muted": "#8B5CF6",
    "--sidebar-icon": "#8B5CF6",
    "--sidebar-icon-active": "#A855F7",
    "--sidebar-item-hover-bg": "#111633",
    "--sidebar-item-active-bg": "#2E1065",
    "--sidebar-item-active-text": "#C084FC",
    "--sidebar-border": "#4C1D95",
    "--sidebar-profile-bg": "#080A1A",
  },
};

export const accentColors: { [key: string]: string } = {
  blue: "#2563EB",
  purple: "#8B5CF6",
  green: "#10B981",
  orange: "#F97316",
  pink: "#EC4899",
  teal: "#14B8A6",
};

export function ThemeProvider({ children }: { children: ReactNode }) {
  const [theme, setThemeState] = useState<ThemePalette>(() => {
    const saved = sessionStorage.getItem("theme-palette");
    return (saved as ThemePalette) || "light";
  });

  const [accentColor, setAccentColorState] = useState(() => {
    const saved = sessionStorage.getItem("accent-color");
    return saved || "blue";
  });

  useEffect(() => {
    const root = document.documentElement;
    const themeColors = themes[theme];

    // Apply theme colors
    Object.entries(themeColors).forEach(([key, value]) => {
      root.style.setProperty(key, value);
    });

    // Legacy variable mapping for backward compatibility
    const legacyMappings: Record<string, string> = {
      "--background": themeColors["--bg-app"] || "",
      "--foreground": themeColors["--text-primary"] || "",
      "--card": themeColors["--bg-surface"] || "",
      "--card-foreground": themeColors["--text-primary"] || "",
      "--popover": themeColors["--bg-dropdown"] || "",
      "--popover-foreground": themeColors["--text-primary"] || "",
      "--primary": themeColors["--accent-primary"] || "",
      "--primary-foreground": themeColors["--text-inverse"] || "",
      "--primary-hover": themeColors["--accent-hover"] || "",
      "--primary-active": themeColors["--accent-active"] || "",
      "--secondary": themeColors["--accent-secondary"] || "",
      "--secondary-foreground": themeColors["--text-inverse"] || "",
      "--muted": themeColors["--bg-surface-alt"] || "",
      "--muted-foreground": themeColors["--text-muted"] || "",
      "--accent": themeColors["--accent-primary"] || "",
      "--accent-foreground": themeColors["--text-inverse"] || "",
      "--destructive": themeColors["--status-error"] || "",
      "--destructive-foreground": themeColors["--text-inverse"] || "",
      "--destructive-hover": themeColors["--status-error"] || "",
      "--border": themeColors["--border-default"] || "",
      "--input": themeColors["--border-default"] || "",
      "--input-background": themeColors["--bg-surface"] || "",
      "--switch-background": themeColors["--border-default"] || "",
      "--ring": themeColors["--accent-primary"] || "",
      "--sidebar": themeColors["--sidebar-bg"] || "",
      "--sidebar-foreground": themeColors["--sidebar-text"] || "",
      "--sidebar-primary": themeColors["--accent-primary"] || "",
      "--sidebar-primary-foreground": themeColors["--text-inverse"] || "",
      "--sidebar-accent": themeColors["--sidebar-item-active-bg"] || "",
      "--sidebar-accent-foreground": themeColors["--sidebar-icon-active"] || "",
      "--sidebar-border": themeColors["--sidebar-border"] || "",
      "--surface-hover": themeColors["--sidebar-item-hover-bg"] || "",
      "--chart-1": themeColors["--chart-primary"] || "",
      "--chart-2": themeColors["--chart-secondary"] || "",
      "--chart-3": themeColors["--accent-primary"] || "",
      "--chart-4": themeColors["--chart-warning"] || "",
      "--chart-5": themeColors["--chart-error"] || "",
      "--success": themeColors["--status-success"] || "",
      "--success-bg": `${themeColors["--status-success"]}20` || "",
      "--warning": themeColors["--status-warning"] || "",
      "--warning-bg": `${themeColors["--status-warning"]}20` || "",
      "--error": themeColors["--status-error"] || "",
      "--error-bg": `${themeColors["--status-error"]}20` || "",
    };

    Object.entries(legacyMappings).forEach(([key, value]) => {
      root.style.setProperty(key, value);
    });

    // Apply accent color override for primary (exclude specialized themes)
    const selectedAccent = accentColors[accentColor];
    const themesWithoutAccentOverride = [
      "high-contrast",
      "indigo-pulse",
      "sales-ignite",
      "growth-analytics",
      "enterprise-slate",
      "realty-premium",
      "urban-blue",
      "ai-neon",
    ];
    if (selectedAccent && !themesWithoutAccentOverride.includes(theme)) {
      root.style.setProperty("--accent-primary", selectedAccent);
      root.style.setProperty("--primary", selectedAccent);
      root.style.setProperty("--sidebar-primary", selectedAccent);
      root.style.setProperty("--ring", selectedAccent);
      root.style.setProperty("--chart-primary", selectedAccent);
      root.style.setProperty("--chart-1", selectedAccent);
      root.style.setProperty("--sidebar-icon-active", selectedAccent);
    }

    // Save to session storage
    sessionStorage.setItem("theme-palette", theme);
    sessionStorage.setItem("accent-color", accentColor);
  }, [theme, accentColor]);

  const setTheme = (newTheme: ThemePalette) => {
    setThemeState(newTheme);
  };

  const setAccentColor = (color: string) => {
    setAccentColorState(color);
  };

  return (
    <ThemeContext.Provider value={{ theme, setTheme, accentColor, setAccentColor }}>
      {children}
    </ThemeContext.Provider>
  );
}

export function useTheme() {
  const context = useContext(ThemeContext);
  if (context === undefined) {
    throw new Error("useTheme must be used within a ThemeProvider");
  }
  return context;
}
