// Comprehensive Clinical Laboratory Test Catalog & Metadata System
// Supporting complete parameter coverage across all 17 clinical categories

export type LabValueType =
  | "numeric"
  | "qualitative"
  | "text"
  | "enum"
  | "ratio"
  | "multiline_text";

export interface LabTestDef {
  id: string;
  name: string;
  shortName?: string;
  category: string;
  defaultUnit: string;
  allowedUnits: string[];
  valueType: LabValueType;
  refMin?: number;
  refMax?: number;
  refText?: string;
  qualitativeOptions?: string[];
  aliases?: string[];
}

export interface LabCategoryDef {
  id: string;
  name: string;
  description?: string;
}

export const LAB_CATEGORIES: LabCategoryDef[] = [
  { id: "cbc", name: "Complete Blood Count (CBC)" },
  { id: "diabetes", name: "Diabetes Profile" },
  { id: "urine", name: "Urine Routine and Microscopy" },
  { id: "kft", name: "Kidney Function Test" },
  { id: "lft", name: "Liver Function Test" },
  { id: "lipid", name: "Lipid Profile" },
  { id: "fasting_lipid", name: "Fasting Lipid Profile" },
  { id: "thyroid", name: "Thyroid Function Profile" },
  { id: "pcos", name: "Fertility/PCOS Profile" },
  { id: "imaging", name: "Routine Imaging and Histopath" },
  { id: "serology", name: "Blood grp & Serology" },
  { id: "electrolytes", name: "Serum Electrolytes" },
  { id: "vitamins", name: "Vitamin & Minerals" },
  { id: "fever", name: "Fever Profile" },
  { id: "iron", name: "Iron Profile" },
  { id: "pft", name: "Pulmonary Function Tests" },
  { id: "cardiac", name: "Cardiac & Inflammatory Profile" },
];

export const LAB_TESTS_CATALOG: LabTestDef[] = [
  // ─────────────────────────────────────────────────────────────
  // 1. COMPLETE BLOOD COUNT (CBC) — 17 Parameters
  // ─────────────────────────────────────────────────────────────
  {
    id: "hb",
    name: "Hemoglobin (Hb)",
    shortName: "Hb",
    category: "Complete Blood Count (CBC)",
    defaultUnit: "g/dL",
    allowedUnits: ["g/dL", "g/L"],
    valueType: "numeric",
    refMin: 12.0,
    refMax: 16.5,
    aliases: ["hemoglobin", "hb", "hgb"],
  },
  {
    id: "rbc_count",
    name: "Total RBC Count",
    shortName: "RBC",
    category: "Complete Blood Count (CBC)",
    defaultUnit: "mil/uL",
    allowedUnits: ["mil/uL", "10^6/uL", "x10^12/L"],
    valueType: "numeric",
    refMin: 3.8,
    refMax: 5.8,
    aliases: ["rbc", "red blood cells", "erythrocytes"],
  },
  {
    id: "pcv",
    name: "PCV (Packed Cell Volume) / Hematocrit",
    shortName: "PCV",
    category: "Complete Blood Count (CBC)",
    defaultUnit: "%",
    allowedUnits: ["%", "L/L"],
    valueType: "numeric",
    refMin: 36.0,
    refMax: 50.0,
    aliases: ["hematocrit", "pcv", "hct"],
  },
  {
    id: "mcv",
    name: "MCV (Mean Corpuscular Volume)",
    shortName: "MCV",
    category: "Complete Blood Count (CBC)",
    defaultUnit: "fL",
    allowedUnits: ["fL", "um^3"],
    valueType: "numeric",
    refMin: 80.0,
    refMax: 100.0,
    aliases: ["mcv"],
  },
  {
    id: "mch",
    name: "MCH (Mean Corpuscular Hemoglobin)",
    shortName: "MCH",
    category: "Complete Blood Count (CBC)",
    defaultUnit: "pg",
    allowedUnits: ["pg"],
    valueType: "numeric",
    refMin: 27.0,
    refMax: 33.0,
    aliases: ["mch"],
  },
  {
    id: "mchc",
    name: "MCHC (Mean Corpuscular Hemoglobin Concentration)",
    shortName: "MCHC",
    category: "Complete Blood Count (CBC)",
    defaultUnit: "g/dL",
    allowedUnits: ["g/dL", "g/L"],
    valueType: "numeric",
    refMin: 32.0,
    refMax: 36.0,
    aliases: ["mchc"],
  },
  {
    id: "tlc",
    name: "Total Leucocyte Count (TLC / WBC)",
    shortName: "TLC",
    category: "Complete Blood Count (CBC)",
    defaultUnit: "/cumm",
    allowedUnits: ["/cumm", "10^3/uL", "x10^9/L"],
    valueType: "numeric",
    refMin: 4000,
    refMax: 11000,
    aliases: ["tlc", "wbc", "total white count"],
  },
  {
    id: "neutrophils_pct",
    name: "Neutrophils %, Blood",
    shortName: "Neutrophils %",
    category: "Complete Blood Count (CBC)",
    defaultUnit: "%",
    allowedUnits: ["%"],
    valueType: "numeric",
    refMin: 40,
    refMax: 75,
    aliases: ["neutrophils", "polys", "segs"],
  },
  {
    id: "lymphocytes_pct",
    name: "Lymphocytes %, Blood",
    shortName: "Lymphocytes %",
    category: "Complete Blood Count (CBC)",
    defaultUnit: "%",
    allowedUnits: ["%"],
    valueType: "numeric",
    refMin: 20,
    refMax: 45,
    aliases: ["lymphocytes", "lymphs"],
  },
  {
    id: "eosinophils_pct",
    name: "Eosinophils %, Blood",
    shortName: "Eosinophils %",
    category: "Complete Blood Count (CBC)",
    defaultUnit: "%",
    allowedUnits: ["%"],
    valueType: "numeric",
    refMin: 1,
    refMax: 6,
    aliases: ["eosinophils", "eos"],
  },
  {
    id: "monocytes_pct",
    name: "Monocytes %, Blood",
    shortName: "Monocytes %",
    category: "Complete Blood Count (CBC)",
    defaultUnit: "%",
    allowedUnits: ["%"],
    valueType: "numeric",
    refMin: 2,
    refMax: 10,
    aliases: ["monocytes", "monos"],
  },
  {
    id: "basophils_pct",
    name: "Basophils %, Blood",
    shortName: "Basophils %",
    category: "Complete Blood Count (CBC)",
    defaultUnit: "%",
    allowedUnits: ["%"],
    valueType: "numeric",
    refMin: 0,
    refMax: 2,
    aliases: ["basophils", "basos"],
  },
  {
    id: "eosinophils_abs",
    name: "Eosinophils Absolute Count, Blood",
    shortName: "AEC",
    category: "Complete Blood Count (CBC)",
    defaultUnit: "/cumm",
    allowedUnits: ["/cumm", "10^3/uL"],
    valueType: "numeric",
    refMin: 40,
    refMax: 440,
    aliases: ["aec", "absolute eosinophil count"],
  },
  {
    id: "rdw",
    name: "RDW (Red Cell Distribution Width)",
    shortName: "RDW",
    category: "Complete Blood Count (CBC)",
    defaultUnit: "%",
    allowedUnits: ["%", "fL"],
    valueType: "numeric",
    refMin: 11.5,
    refMax: 14.5,
    aliases: ["rdw", "rdw-cv"],
  },
  {
    id: "platelet_count",
    name: "Platelet Count (PC), Blood",
    shortName: "Platelets",
    category: "Complete Blood Count (CBC)",
    defaultUnit: "Lakh/cumm",
    allowedUnits: ["Lakh/cumm", "10^3/uL", "x10^9/L"],
    valueType: "numeric",
    refMin: 1.5,
    refMax: 4.5,
    aliases: ["platelets", "pc", "thrombocytes"],
  },
  {
    id: "esr",
    name: "Erythrocyte Sedimentation Rate (ESR)",
    shortName: "ESR",
    category: "Complete Blood Count (CBC)",
    defaultUnit: "mm/1st hr",
    allowedUnits: ["mm/1st hr", "mm/hr"],
    valueType: "numeric",
    refMin: 0,
    refMax: 20,
    aliases: ["esr", "sed rate"],
  },
  {
    id: "pbs",
    name: "PBS (Peripheral Blood Smear)",
    shortName: "PBS",
    category: "Complete Blood Count (CBC)",
    defaultUnit: "--",
    allowedUnits: ["--", "Text"],
    valueType: "text",
    aliases: ["pbs", "peripheral smear", "blood film"],
  },

  // ─────────────────────────────────────────────────────────────
  // 2. DIABETES PROFILE
  // ─────────────────────────────────────────────────────────────
  {
    id: "fbs",
    name: "Fasting Blood Glucose (FBS)",
    shortName: "FBS",
    category: "Diabetes Profile",
    defaultUnit: "mg/dL",
    allowedUnits: ["mg/dL", "mmol/L"],
    valueType: "numeric",
    refMin: 70,
    refMax: 99,
    aliases: ["fasting sugar", "fbs", "fasting blood glucose"],
  },
  {
    id: "ppbs",
    name: "Post Prandial Blood Glucose (PPBS)",
    shortName: "PPBS",
    category: "Diabetes Profile",
    defaultUnit: "mg/dL",
    allowedUnits: ["mg/dL", "mmol/L"],
    valueType: "numeric",
    refMin: 70,
    refMax: 140,
    aliases: ["ppbs", "post prandial sugar"],
  },
  {
    id: "rbs",
    name: "Random Blood Glucose (RBS)",
    shortName: "RBS",
    category: "Diabetes Profile",
    defaultUnit: "mg/dL",
    allowedUnits: ["mg/dL", "mmol/L"],
    valueType: "numeric",
    refMin: 70,
    refMax: 140,
    aliases: ["rbs", "random sugar"],
  },
  {
    id: "hba1c",
    name: "HbA1c (Glycated Hemoglobin)",
    shortName: "HbA1c",
    category: "Diabetes Profile",
    defaultUnit: "%",
    allowedUnits: ["%", "mmol/mol"],
    valueType: "numeric",
    refMin: 4.0,
    refMax: 5.6,
    aliases: ["hba1c", "glycated hemoglobin", "a1c"],
  },
  {
    id: "eag",
    name: "Estimated Average Glucose (eAG)",
    shortName: "eAG",
    category: "Diabetes Profile",
    defaultUnit: "mg/dL",
    allowedUnits: ["mg/dL", "mmol/L"],
    valueType: "numeric",
    refMin: 70,
    refMax: 126,
    aliases: ["eag", "average glucose"],
  },
  {
    id: "fasting_insulin",
    name: "Fasting Serum Insulin",
    shortName: "Insulin",
    category: "Diabetes Profile",
    defaultUnit: "uIU/mL",
    allowedUnits: ["uIU/mL", "pmol/L"],
    valueType: "numeric",
    refMin: 2.6,
    refMax: 24.9,
    aliases: ["insulin", "fasting insulin"],
  },
  {
    id: "c_peptide",
    name: "C-Peptide Fasting",
    shortName: "C-Peptide",
    category: "Diabetes Profile",
    defaultUnit: "ng/mL",
    allowedUnits: ["ng/mL", "nmol/L"],
    valueType: "numeric",
    refMin: 0.8,
    refMax: 3.1,
    aliases: ["c-peptide", "c peptide"],
  },
  {
    id: "homa_ir",
    name: "HOMA-IR (Insulin Resistance Index)",
    shortName: "HOMA-IR",
    category: "Diabetes Profile",
    defaultUnit: "Index",
    allowedUnits: ["Index"],
    valueType: "numeric",
    refMin: 0.5,
    refMax: 1.9,
    aliases: ["homa ir", "insulin resistance"],
  },

  // ─────────────────────────────────────────────────────────────
  // 3. URINE ROUTINE AND MICROSCOPY — 16 Parameters
  // ─────────────────────────────────────────────────────────────
  {
    id: "urine_colour",
    name: "Urine Colour",
    category: "Urine Routine and Microscopy",
    defaultUnit: "--",
    allowedUnits: ["--"],
    valueType: "enum",
    qualitativeOptions: ["Pale Yellow", "Straw", "Yellow", "Amber", "Dark Yellow", "Reddish", "Cloudy"],
  },
  {
    id: "urine_appearance",
    name: "Urine Appearance / Transparency",
    category: "Urine Routine and Microscopy",
    defaultUnit: "--",
    allowedUnits: ["--"],
    valueType: "enum",
    qualitativeOptions: ["Clear", "Slightly Turbid", "Turbid", "Hazy"],
  },
  {
    id: "urine_sp_gravity",
    name: "Specific Gravity",
    category: "Urine Routine and Microscopy",
    defaultUnit: "--",
    allowedUnits: ["--"],
    valueType: "numeric",
    refMin: 1.005,
    refMax: 1.030,
  },
  {
    id: "urine_ph",
    name: "Urine pH",
    category: "Urine Routine and Microscopy",
    defaultUnit: "pH",
    allowedUnits: ["pH"],
    valueType: "numeric",
    refMin: 5.0,
    refMax: 8.0,
  },
  {
    id: "urine_protein",
    name: "Protein (Albumin), Urine",
    category: "Urine Routine and Microscopy",
    defaultUnit: "--",
    allowedUnits: ["--", "mg/dL"],
    valueType: "qualitative",
    qualitativeOptions: ["Nil / Negative", "Trace", "1+ (30 mg/dL)", "2+ (100 mg/dL)", "3+ (300 mg/dL)", "4+ (1000 mg/dL)"],
  },
  {
    id: "urine_glucose",
    name: "Glucose (Sugar), Urine",
    category: "Urine Routine and Microscopy",
    defaultUnit: "--",
    allowedUnits: ["--"],
    valueType: "qualitative",
    qualitativeOptions: ["Nil / Negative", "Trace", "1+", "2+", "3+", "4+"],
  },
  {
    id: "urine_ketones",
    name: "Ketones (Acetoacetate), Urine",
    category: "Urine Routine and Microscopy",
    defaultUnit: "--",
    allowedUnits: ["--"],
    valueType: "qualitative",
    qualitativeOptions: ["Negative", "Trace", "Small", "Moderate", "Large"],
  },
  {
    id: "urine_blood",
    name: "Occult Blood / Hemoglobin, Urine",
    category: "Urine Routine and Microscopy",
    defaultUnit: "--",
    allowedUnits: ["--"],
    valueType: "qualitative",
    qualitativeOptions: ["Negative", "Trace", "Moderate", "Large"],
  },
  {
    id: "urine_nitrite",
    name: "Nitrite, Urine",
    category: "Urine Routine and Microscopy",
    defaultUnit: "--",
    allowedUnits: ["--"],
    valueType: "qualitative",
    qualitativeOptions: ["Negative", "Positive"],
  },
  {
    id: "urine_leukocyte_esterase",
    name: "Leukocyte Esterase, Urine",
    category: "Urine Routine and Microscopy",
    defaultUnit: "--",
    allowedUnits: ["--"],
    valueType: "qualitative",
    qualitativeOptions: ["Negative", "Trace", "Small", "Moderate", "Large"],
  },
  {
    id: "urine_pus_cells",
    name: "Pus Cells (WBC), Microscopy",
    category: "Urine Routine and Microscopy",
    defaultUnit: "/HPF",
    allowedUnits: ["/HPF"],
    valueType: "numeric",
    refMin: 0,
    refMax: 5,
  },
  {
    id: "urine_rbc",
    name: "Red Blood Cells (RBC), Microscopy",
    category: "Urine Routine and Microscopy",
    defaultUnit: "/HPF",
    allowedUnits: ["/HPF"],
    valueType: "numeric",
    refMin: 0,
    refMax: 2,
  },
  {
    id: "urine_epithelial",
    name: "Epithelial Cells, Microscopy",
    category: "Urine Routine and Microscopy",
    defaultUnit: "/HPF",
    allowedUnits: ["/HPF"],
    valueType: "numeric",
    refMin: 0,
    refMax: 5,
  },
  {
    id: "urine_casts",
    name: "Casts, Urine",
    category: "Urine Routine and Microscopy",
    defaultUnit: "--",
    allowedUnits: ["--"],
    valueType: "enum",
    qualitativeOptions: ["Nil / Not Seen", "Hyaline Casts", "Granular Casts", "RBC Casts", "WBC Casts"],
  },
  {
    id: "urine_crystals",
    name: "Crystals, Urine",
    category: "Urine Routine and Microscopy",
    defaultUnit: "--",
    allowedUnits: ["--"],
    valueType: "enum",
    qualitativeOptions: ["Nil / Not Seen", "Calcium Oxalate", "Uric Acid", "Triple Phosphate", "Amorphous"],
  },
  {
    id: "urine_bacteria",
    name: "Bacteria, Urine",
    category: "Urine Routine and Microscopy",
    defaultUnit: "--",
    allowedUnits: ["--"],
    valueType: "enum",
    qualitativeOptions: ["Nil / Absent", "Few (+)", "Moderate (++)", "Many (+++)"],
  },

  // ─────────────────────────────────────────────────────────────
  // 4. KIDNEY FUNCTION TEST (KFT) — Complete Coverage from Reference
  // ─────────────────────────────────────────────────────────────
  {
    id: "blood_urea",
    name: "Blood Urea",
    shortName: "Urea",
    category: "Kidney Function Test",
    defaultUnit: "mg/dL",
    allowedUnits: ["mg/dL", "mmol/L"],
    valueType: "numeric",
    refMin: 15.0,
    refMax: 40.0,
    aliases: ["urea", "blood urea"],
  },
  {
    id: "creatinine_serum",
    name: "Creatinine Serum",
    shortName: "Creatinine",
    category: "Kidney Function Test",
    defaultUnit: "mg/dL",
    allowedUnits: ["mg/dL", "umol/L"],
    valueType: "numeric",
    refMin: 0.6,
    refMax: 1.2,
    aliases: ["creatinine", "serum creatinine", "creat"],
  },
  {
    id: "uric_acid",
    name: "Uric Acid, Serum",
    shortName: "Uric Acid",
    category: "Kidney Function Test",
    defaultUnit: "mg/dL",
    allowedUnits: ["mg/dL", "umol/L"],
    valueType: "numeric",
    refMin: 3.5,
    refMax: 7.2,
    aliases: ["uric acid"],
  },
  {
    id: "bun",
    name: "BUN (Blood Urea Nitrogen)",
    shortName: "BUN",
    category: "Kidney Function Test",
    defaultUnit: "mg/dL",
    allowedUnits: ["mg/dL", "mmol/L"],
    valueType: "numeric",
    refMin: 7.0,
    refMax: 20.0,
    aliases: ["bun", "urea nitrogen"],
  },
  {
    id: "bun_creatinine_ratio",
    name: "BUN / Serum Creatinine Ratio",
    shortName: "BUN/Cr",
    category: "Kidney Function Test",
    defaultUnit: "Ratio",
    allowedUnits: ["Ratio"],
    valueType: "numeric",
    refMin: 10.0,
    refMax: 20.0,
  },
  {
    id: "egfr",
    name: "eGFR (Glomerular Filtration Rate estimated)",
    shortName: "eGFR",
    category: "Kidney Function Test",
    defaultUnit: "mL/min/1.73m²",
    allowedUnits: ["mL/min/1.73m²"],
    valueType: "numeric",
    refMin: 90.0,
    refMax: 130.0,
    aliases: ["egfr", "gfr"],
  },
  {
    id: "sodium_kft",
    name: "Sodium (Na), Serum",
    shortName: "Na+",
    category: "Kidney Function Test",
    defaultUnit: "mmol/L",
    allowedUnits: ["mmol/L", "mEq/L"],
    valueType: "numeric",
    refMin: 135.0,
    refMax: 145.0,
    aliases: ["sodium", "na"],
  },
  {
    id: "potassium_kft",
    name: "Potassium (K), Serum",
    shortName: "K+",
    category: "Kidney Function Test",
    defaultUnit: "mmol/L",
    allowedUnits: ["mmol/L", "mEq/L"],
    valueType: "numeric",
    refMin: 3.5,
    refMax: 5.1,
    aliases: ["potassium", "k"],
  },
  {
    id: "chloride_kft",
    name: "Chloride (Cl), Serum",
    shortName: "Cl-",
    category: "Kidney Function Test",
    defaultUnit: "mmol/L",
    allowedUnits: ["mmol/L", "mEq/L"],
    valueType: "numeric",
    refMin: 96.0,
    refMax: 106.0,
    aliases: ["chloride", "cl"],
  },
  {
    id: "calcium_kft",
    name: "Calcium, Serum",
    shortName: "Ca",
    category: "Kidney Function Test",
    defaultUnit: "mg/dL",
    allowedUnits: ["mg/dL", "mmol/L"],
    valueType: "numeric",
    refMin: 8.5,
    refMax: 10.5,
  },
  {
    id: "phosphorus_kft",
    name: "Phosphorus, Serum",
    shortName: "Phosphorus",
    category: "Kidney Function Test",
    defaultUnit: "mg/dL",
    allowedUnits: ["mg/dL", "mmol/L"],
    valueType: "numeric",
    refMin: 2.5,
    refMax: 4.5,
  },
  {
    id: "bicarbonate_kft",
    name: "Bicarbonate, blood (HCO3)",
    shortName: "HCO3",
    category: "Kidney Function Test",
    defaultUnit: "mmol/L",
    allowedUnits: ["mmol/L", "mEq/L"],
    valueType: "numeric",
    refMin: 22.0,
    refMax: 29.0,
  },
  {
    id: "albumin_spot_urine",
    name: "Albumin, Spot Urine (Quantitative)",
    shortName: "Urine Albumin",
    category: "Kidney Function Test",
    defaultUnit: "mg/L",
    allowedUnits: ["mg/L", "ug/min"],
    valueType: "numeric",
    refMin: 0.0,
    refMax: 20.0,
  },
  {
    id: "creatinine_spot_urine",
    name: "Creatinine, Spot Urine",
    shortName: "Urine Creatinine",
    category: "Kidney Function Test",
    defaultUnit: "mg/dL",
    allowedUnits: ["mg/dL", "g/L"],
    valueType: "numeric",
    refMin: 20.0,
    refMax: 320.0,
  },
  {
    id: "microalbuminuria",
    name: "Microalbuminuria Test",
    shortName: "Microalbumin",
    category: "Kidney Function Test",
    defaultUnit: "mg/24hr",
    allowedUnits: ["mg/24hr", "mg/L"],
    valueType: "numeric",
    refMin: 0.0,
    refMax: 30.0,
  },
  {
    id: "acr_urine",
    name: "Albumin Creatinine Ratio (ACR), Spot Urine",
    shortName: "UACR",
    category: "Kidney Function Test",
    defaultUnit: "mg/g",
    allowedUnits: ["mg/g", "mg/mmol"],
    valueType: "numeric",
    refMin: 0.0,
    refMax: 30.0,
    aliases: ["uacr", "acr", "albumin creatinine ratio"],
  },

  // ─────────────────────────────────────────────────────────────
  // 5. LIVER FUNCTION TEST (LFT) — 11 Parameters
  // ─────────────────────────────────────────────────────────────
  {
    id: "bilirubin_total",
    name: "Bilirubin Total, Serum",
    shortName: "Total Bilirubin",
    category: "Liver Function Test",
    defaultUnit: "mg/dL",
    allowedUnits: ["mg/dL", "umol/L"],
    valueType: "numeric",
    refMin: 0.2,
    refMax: 1.2,
    aliases: ["bilirubin total", "total bili"],
  },
  {
    id: "bilirubin_direct",
    name: "Bilirubin Direct (Conjugated)",
    shortName: "Direct Bilirubin",
    category: "Liver Function Test",
    defaultUnit: "mg/dL",
    allowedUnits: ["mg/dL", "umol/L"],
    valueType: "numeric",
    refMin: 0.0,
    refMax: 0.3,
  },
  {
    id: "bilirubin_indirect",
    name: "Bilirubin Indirect (Unconjugated)",
    shortName: "Indirect Bilirubin",
    category: "Liver Function Test",
    defaultUnit: "mg/dL",
    allowedUnits: ["mg/dL", "umol/L"],
    valueType: "numeric",
    refMin: 0.2,
    refMax: 0.8,
  },
  {
    id: "sgot_ast",
    name: "AST / SGOT (Aspartate Aminotransferase)",
    shortName: "SGOT (AST)",
    category: "Liver Function Test",
    defaultUnit: "U/L",
    allowedUnits: ["U/L", "IU/L"],
    valueType: "numeric",
    refMin: 5,
    refMax: 40,
    aliases: ["ast", "sgot"],
  },
  {
    id: "sgpt_alt",
    name: "ALT / SGPT (Alanine Aminotransferase)",
    shortName: "SGPT (ALT)",
    category: "Liver Function Test",
    defaultUnit: "U/L",
    allowedUnits: ["U/L", "IU/L"],
    valueType: "numeric",
    refMin: 7,
    refMax: 56,
    aliases: ["alt", "sgpt"],
  },
  {
    id: "alp",
    name: "Alkaline Phosphatase (ALP)",
    shortName: "ALP",
    category: "Liver Function Test",
    defaultUnit: "U/L",
    allowedUnits: ["U/L", "IU/L"],
    valueType: "numeric",
    refMin: 44,
    refMax: 147,
    aliases: ["alp", "alk phos"],
  },
  {
    id: "ggt",
    name: "Gamma GT / GGT (Gamma Glutamyl Transferase)",
    shortName: "GGT",
    category: "Liver Function Test",
    defaultUnit: "U/L",
    allowedUnits: ["U/L", "IU/L"],
    valueType: "numeric",
    refMin: 9,
    refMax: 48,
    aliases: ["ggt", "gamma gt"],
  },
  {
    id: "total_protein",
    name: "Total Protein, Serum",
    shortName: "Total Protein",
    category: "Liver Function Test",
    defaultUnit: "g/dL",
    allowedUnits: ["g/dL", "g/L"],
    valueType: "numeric",
    refMin: 6.0,
    refMax: 8.3,
  },
  {
    id: "albumin_serum",
    name: "Albumin, Serum",
    shortName: "Albumin",
    category: "Liver Function Test",
    defaultUnit: "g/dL",
    allowedUnits: ["g/dL", "g/L"],
    valueType: "numeric",
    refMin: 3.5,
    refMax: 5.2,
  },
  {
    id: "globulin_serum",
    name: "Globulin, Serum",
    shortName: "Globulin",
    category: "Liver Function Test",
    defaultUnit: "g/dL",
    allowedUnits: ["g/dL", "g/L"],
    valueType: "numeric",
    refMin: 2.0,
    refMax: 3.5,
  },
  {
    id: "ag_ratio",
    name: "Albumin / Globulin (A/G) Ratio",
    shortName: "A/G Ratio",
    category: "Liver Function Test",
    defaultUnit: "Ratio",
    allowedUnits: ["Ratio"],
    valueType: "numeric",
    refMin: 1.1,
    refMax: 2.5,
  },

  // ─────────────────────────────────────────────────────────────
  // 6. LIPID PROFILE & 7. FASTING LIPID PROFILE — 10 Parameters
  // ─────────────────────────────────────────────────────────────
  {
    id: "cholesterol_total",
    name: "Total Cholesterol",
    shortName: "Total Chol",
    category: "Lipid Profile",
    defaultUnit: "mg/dL",
    allowedUnits: ["mg/dL", "mmol/L"],
    valueType: "numeric",
    refMin: 125,
    refMax: 200,
    aliases: ["cholesterol", "total cholesterol"],
  },
  {
    id: "hdl_cholesterol",
    name: "HDL Cholesterol, Serum",
    shortName: "HDL",
    category: "Lipid Profile",
    defaultUnit: "mg/dL",
    allowedUnits: ["mg/dL", "mmol/L"],
    valueType: "numeric",
    refMin: 40,
    refMax: 60,
    aliases: ["hdl", "good cholesterol"],
  },
  {
    id: "ldl_cholesterol",
    name: "LDL Cholesterol, Serum",
    shortName: "LDL",
    category: "Lipid Profile",
    defaultUnit: "mg/dL",
    allowedUnits: ["mg/dL", "mmol/L"],
    valueType: "numeric",
    refMin: 0,
    refMax: 100,
    aliases: ["ldl", "bad cholesterol"],
  },
  {
    id: "triglycerides",
    name: "Triglycerides (TGs)",
    shortName: "TGs",
    category: "Lipid Profile",
    defaultUnit: "mg/dL",
    allowedUnits: ["mg/dL", "mmol/L"],
    valueType: "numeric",
    refMin: 0,
    refMax: 150,
    aliases: ["triglycerides", "tg", "tgs"],
  },
  {
    id: "vldl_cholesterol",
    name: "VLDL (Very Low Density Lipoprotein)",
    shortName: "VLDL",
    category: "Lipid Profile",
    defaultUnit: "mg/dL",
    allowedUnits: ["mg/dL", "mmol/L"],
    valueType: "numeric",
    refMin: 5,
    refMax: 30,
    aliases: ["vldl"],
  },
  {
    id: "non_hdl_cholesterol",
    name: "Non-HDL Cholesterol",
    shortName: "Non-HDL",
    category: "Lipid Profile",
    defaultUnit: "mg/dL",
    allowedUnits: ["mg/dL", "mmol/L"],
    valueType: "numeric",
    refMin: 0,
    refMax: 130,
    aliases: ["non hdl"],
  },
  {
    id: "chol_hdl_ratio",
    name: "Total Cholesterol / HDL Cholesterol Ratio",
    shortName: "Chol/HDL",
    category: "Lipid Profile",
    defaultUnit: "Ratio",
    allowedUnits: ["Ratio"],
    valueType: "numeric",
    refMin: 3.0,
    refMax: 5.0,
  },
  {
    id: "tg_hdl_ratio",
    name: "Triglyceride / HDL Cholesterol Ratio",
    shortName: "TG/HDL",
    category: "Lipid Profile",
    defaultUnit: "Ratio",
    allowedUnits: ["Ratio"],
    valueType: "numeric",
    refMin: 0.5,
    refMax: 3.0,
  },
  {
    id: "ldl_hdl_ratio",
    name: "LDL Cholesterol / HDL Cholesterol Ratio",
    shortName: "LDL/HDL",
    category: "Lipid Profile",
    defaultUnit: "Ratio",
    allowedUnits: ["Ratio"],
    valueType: "numeric",
    refMin: 1.0,
    refMax: 3.5,
  },
  {
    id: "apob",
    name: "Apolipoprotein B (Apo B)",
    shortName: "Apo B",
    category: "Lipid Profile",
    defaultUnit: "mg/dL",
    allowedUnits: ["mg/dL", "g/L"],
    valueType: "numeric",
    refMin: 60,
    refMax: 130,
  },

  // Fasting Lipid Profile shared mapping
  {
    id: "fasting_total_chol",
    name: "Total Cholesterol (Fasting)",
    shortName: "Fasting Chol",
    category: "Fasting Lipid Profile",
    defaultUnit: "mg/dL",
    allowedUnits: ["mg/dL", "mmol/L"],
    valueType: "numeric",
    refMin: 125,
    refMax: 200,
  },
  {
    id: "fasting_hdl",
    name: "HDL Cholesterol (Fasting)",
    shortName: "Fasting HDL",
    category: "Fasting Lipid Profile",
    defaultUnit: "mg/dL",
    allowedUnits: ["mg/dL", "mmol/L"],
    valueType: "numeric",
    refMin: 40,
    refMax: 60,
  },
  {
    id: "fasting_ldl",
    name: "LDL Cholesterol (Fasting)",
    shortName: "Fasting LDL",
    category: "Fasting Lipid Profile",
    defaultUnit: "mg/dL",
    allowedUnits: ["mg/dL", "mmol/L"],
    valueType: "numeric",
    refMin: 0,
    refMax: 100,
  },
  {
    id: "fasting_tg",
    name: "Triglycerides (Fasting)",
    shortName: "Fasting TG",
    category: "Fasting Lipid Profile",
    defaultUnit: "mg/dL",
    allowedUnits: ["mg/dL", "mmol/L"],
    valueType: "numeric",
    refMin: 0,
    refMax: 150,
  },

  // ─────────────────────────────────────────────────────────────
  // 8. THYROID FUNCTION PROFILE — 8 Parameters from Reference
  // ─────────────────────────────────────────────────────────────
  {
    id: "tsh",
    name: "TSH (Thyroid Stimulating Hormone)",
    shortName: "TSH",
    category: "Thyroid Function Profile",
    defaultUnit: "u[IU]/mL",
    allowedUnits: ["u[IU]/mL", "[IU]/mL", "mIU/L"],
    valueType: "numeric",
    refMin: 0.4,
    refMax: 4.2,
    aliases: ["tsh", "thyroid"],
  },
  {
    id: "total_t4",
    name: "Total Thyroxine (T4), Serum",
    shortName: "Total T4",
    category: "Thyroid Function Profile",
    defaultUnit: "ug/dL",
    allowedUnits: ["ug/dL", "nmol/L"],
    valueType: "numeric",
    refMin: 4.5,
    refMax: 12.0,
    aliases: ["t4", "total t4"],
  },
  {
    id: "total_t3",
    name: "T3, Total (Triiodothyronine)",
    shortName: "Total T3",
    category: "Thyroid Function Profile",
    defaultUnit: "ng/dL",
    allowedUnits: ["ng/dL", "nmol/L"],
    valueType: "numeric",
    refMin: 80.0,
    refMax: 200.0,
    aliases: ["t3", "total t3"],
  },
  {
    id: "free_t4",
    name: "Free Thyroxine (FT4), Serum",
    shortName: "FT4",
    category: "Thyroid Function Profile",
    defaultUnit: "ng/dL",
    allowedUnits: ["ng/dL", "pmol/L"],
    valueType: "numeric",
    refMin: 0.8,
    refMax: 1.8,
    aliases: ["ft4", "free t4"],
  },
  {
    id: "free_t3",
    name: "T3, Free (Triiodothyronine)",
    shortName: "FT3",
    category: "Thyroid Function Profile",
    defaultUnit: "pg/mL",
    allowedUnits: ["pg/mL", "pmol/L"],
    valueType: "numeric",
    refMin: 2.0,
    refMax: 4.4,
    aliases: ["ft3", "free t3"],
  },
  {
    id: "anti_tpo",
    name: "Anti Thyroperoxidase (TPO) Antibody, Serum",
    shortName: "Anti-TPO",
    category: "Thyroid Function Profile",
    defaultUnit: "[IU]/mL",
    allowedUnits: ["[IU]/mL", "IU/mL"],
    valueType: "numeric",
    refMin: 0.0,
    refMax: 35.0,
    aliases: ["anti tpo", "tpo antibody"],
  },
  {
    id: "tg_ab_quant",
    name: "Thyroglobulin Antibody, Serum (Quantitative)",
    shortName: "TgAb (Quant)",
    category: "Thyroid Function Profile",
    defaultUnit: "[IU]/mL",
    allowedUnits: ["[IU]/mL", "IU/mL"],
    valueType: "numeric",
    refMin: 0.0,
    refMax: 115.0,
  },
  {
    id: "tg_ab_qual",
    name: "Thyroglobulin Antibody, Serum (Qualitative)",
    shortName: "TgAb (Qual)",
    category: "Thyroid Function Profile",
    defaultUnit: "--",
    allowedUnits: ["--", "Qualitative"],
    valueType: "qualitative",
    qualitativeOptions: ["Negative", "Positive", "Borderline"],
  },

  // ─────────────────────────────────────────────────────────────
  // 9. FERTILITY / PCOS PROFILE
  // ─────────────────────────────────────────────────────────────
  {
    id: "fsh",
    name: "FSH (Follicle Stimulating Hormone)",
    shortName: "FSH",
    category: "Fertility/PCOS Profile",
    defaultUnit: "mIU/mL",
    allowedUnits: ["mIU/mL", "IU/L"],
    valueType: "numeric",
    refMin: 3.5,
    refMax: 12.5,
  },
  {
    id: "lh",
    name: "LH (Luteinizing Hormone)",
    shortName: "LH",
    category: "Fertility/PCOS Profile",
    defaultUnit: "mIU/mL",
    allowedUnits: ["mIU/mL", "IU/L"],
    valueType: "numeric",
    refMin: 2.4,
    refMax: 12.6,
  },
  {
    id: "prolactin",
    name: "Prolactin, Serum",
    shortName: "Prolactin",
    category: "Fertility/PCOS Profile",
    defaultUnit: "ng/mL",
    allowedUnits: ["ng/mL", "uIU/mL"],
    valueType: "numeric",
    refMin: 4.8,
    refMax: 23.3,
  },
  {
    id: "amh",
    name: "Anti-Mullerian Hormone (AMH)",
    shortName: "AMH",
    category: "Fertility/PCOS Profile",
    defaultUnit: "ng/mL",
    allowedUnits: ["ng/mL", "pmol/L"],
    valueType: "numeric",
    refMin: 1.0,
    refMax: 4.0,
    aliases: ["amh", "ovarian reserve"],
  },
  {
    id: "total_testosterone",
    name: "Total Testosterone, Serum",
    shortName: "Testosterone",
    category: "Fertility/PCOS Profile",
    defaultUnit: "ng/dL",
    allowedUnits: ["ng/dL", "nmol/L"],
    valueType: "numeric",
    refMin: 15.0,
    refMax: 70.0,
  },
  {
    id: "dhea_s",
    name: "DHEA-Sulfate (DHEA-S)",
    shortName: "DHEA-S",
    category: "Fertility/PCOS Profile",
    defaultUnit: "ug/dL",
    allowedUnits: ["ug/dL", "umol/L"],
    valueType: "numeric",
    refMin: 65.0,
    refMax: 380.0,
  },

  // ─────────────────────────────────────────────────────────────
  // 10. ROUTINE IMAGING AND HISTOPATH
  // ─────────────────────────────────────────────────────────────
  {
    id: "xray_chest",
    name: "Chest X-Ray (PA View)",
    shortName: "CXR",
    category: "Routine Imaging and Histopath",
    defaultUnit: "--",
    allowedUnits: ["--", "Text"],
    valueType: "multiline_text",
  },
  {
    id: "usg_abdomen",
    name: "Ultrasound (USG) Whole Abdomen",
    shortName: "USG Abdomen",
    category: "Routine Imaging and Histopath",
    defaultUnit: "--",
    allowedUnits: ["--", "Text"],
    valueType: "multiline_text",
  },
  {
    id: "ecg_12lead",
    name: "12-Lead Electrocardiogram (ECG)",
    shortName: "ECG",
    category: "Routine Imaging and Histopath",
    defaultUnit: "--",
    allowedUnits: ["--", "Text"],
    valueType: "enum",
    qualitativeOptions: ["Normal Sinus Rhythm", "Sinus Tachycardia", "Sinus Bradycardia", "Arrhythmia", "Ischemic Changes", "Abnormal"],
  },
  {
    id: "histopath_biopsy",
    name: "Histopathology / Biopsy Examination",
    shortName: "Histopath",
    category: "Routine Imaging and Histopath",
    defaultUnit: "--",
    allowedUnits: ["--", "Text"],
    valueType: "multiline_text",
  },

  // ─────────────────────────────────────────────────────────────
  // 11. BLOOD GRP & SEROLOGY — Reference Complete Coverage
  // ─────────────────────────────────────────────────────────────
  {
    id: "abo_rh",
    name: "ABO Grouping and Typing (Blood Group & Rh Type)",
    shortName: "Blood Group",
    category: "Blood grp & Serology",
    defaultUnit: "--",
    allowedUnits: ["--"],
    valueType: "enum",
    qualitativeOptions: ["A Positive (A+)", "A Negative (A-)", "B Positive (B+)", "B Negative (B-)", "O Positive (O+)", "O Negative (O-)", "AB Positive (AB+)", "AB Negative (AB-)"],
    aliases: ["blood group", "abo", "rh"],
  },
  {
    id: "hiv_rapid",
    name: "HIV I & II Antibody (Rapid)",
    shortName: "HIV Rapid",
    category: "Blood grp & Serology",
    defaultUnit: "--",
    allowedUnits: ["--"],
    valueType: "qualitative",
    qualitativeOptions: ["Non-Reactive", "Reactive"],
    aliases: ["hiv", "hiv 1", "hiv 2"],
  },
  {
    id: "hiv_elisa",
    name: "HIV I, Serum (Rapid / ELISA)",
    shortName: "HIV Serum",
    category: "Blood grp & Serology",
    defaultUnit: "--",
    allowedUnits: ["--"],
    valueType: "qualitative",
    qualitativeOptions: ["Negative", "Positive", "Equivocal"],
  },
  {
    id: "hbsag",
    name: "HBsAg (Hepatitis B Surface Antigen)",
    shortName: "HBsAg",
    category: "Blood grp & Serology",
    defaultUnit: "--",
    allowedUnits: ["--"],
    valueType: "qualitative",
    qualitativeOptions: ["Negative / Non-Reactive", "Positive / Reactive"],
    aliases: ["hbsag", "hepatitis b"],
  },
  {
    id: "hcv_ab",
    name: "Hepatitis C (HCV) Total Antibodies (Rapid)",
    shortName: "Anti-HCV",
    category: "Blood grp & Serology",
    defaultUnit: "--",
    allowedUnits: ["--"],
    valueType: "qualitative",
    qualitativeOptions: ["Non-Reactive", "Reactive"],
    aliases: ["hcv", "hepatitis c"],
  },
  {
    id: "vdrl_rpr",
    name: "VDRL Test / RPR for Syphilis",
    shortName: "VDRL",
    category: "Blood grp & Serology",
    defaultUnit: "--",
    allowedUnits: ["--", "Titre"],
    valueType: "qualitative",
    qualitativeOptions: ["Non-Reactive", "Reactive", "Weakly Reactive"],
    aliases: ["vdrl", "syphilis", "rpr"],
  },

  // ─────────────────────────────────────────────────────────────
  // 12. SERUM ELECTROLYTES
  // ─────────────────────────────────────────────────────────────
  {
    id: "sodium_se",
    name: "Sodium (Na+), Serum",
    shortName: "Sodium",
    category: "Serum Electrolytes",
    defaultUnit: "mmol/L",
    allowedUnits: ["mmol/L", "mEq/L"],
    valueType: "numeric",
    refMin: 135.0,
    refMax: 145.0,
  },
  {
    id: "potassium_se",
    name: "Potassium (K+), Serum",
    shortName: "Potassium",
    category: "Serum Electrolytes",
    defaultUnit: "mmol/L",
    allowedUnits: ["mmol/L", "mEq/L"],
    valueType: "numeric",
    refMin: 3.5,
    refMax: 5.1,
  },
  {
    id: "chloride_se",
    name: "Chloride (Cl-), Serum",
    shortName: "Chloride",
    category: "Serum Electrolytes",
    defaultUnit: "mmol/L",
    allowedUnits: ["mmol/L", "mEq/L"],
    valueType: "numeric",
    refMin: 96.0,
    refMax: 106.0,
  },
  {
    id: "bicarbonate_se",
    name: "Bicarbonate (HCO3-), Serum",
    shortName: "Bicarbonate",
    category: "Serum Electrolytes",
    defaultUnit: "mmol/L",
    allowedUnits: ["mmol/L", "mEq/L"],
    valueType: "numeric",
    refMin: 22.0,
    refMax: 29.0,
  },
  {
    id: "magnesium_se",
    name: "Magnesium, Serum",
    shortName: "Magnesium",
    category: "Serum Electrolytes",
    defaultUnit: "mg/dL",
    allowedUnits: ["mg/dL", "mmol/L"],
    valueType: "numeric",
    refMin: 1.7,
    refMax: 2.4,
  },
  {
    id: "anion_gap",
    name: "Anion Gap",
    shortName: "Anion Gap",
    category: "Serum Electrolytes",
    defaultUnit: "mmol/L",
    allowedUnits: ["mmol/L", "mEq/L"],
    valueType: "numeric",
    refMin: 8.0,
    refMax: 16.0,
  },

  // ─────────────────────────────────────────────────────────────
  // 13. VITAMIN & MINERALS — Reference Complete Coverage
  // ─────────────────────────────────────────────────────────────
  {
    id: "vit_d",
    name: "Vitamin D (25 Hydroxy Vitamin D / Vitamin D Total - D2+D3)",
    shortName: "Vitamin D",
    category: "Vitamin & Minerals",
    defaultUnit: "ng/mL",
    allowedUnits: ["ng/mL", "nmol/L"],
    valueType: "numeric",
    refMin: 30.0,
    refMax: 100.0,
    aliases: ["vitamin d", "25 oh vit d", "vit d3"],
  },
  {
    id: "vit_b12",
    name: "Vitamin B12 (Cyanocobalamin)",
    shortName: "Vitamin B12",
    category: "Vitamin & Minerals",
    defaultUnit: "pg/mL",
    allowedUnits: ["pg/mL", "pmol/L"],
    valueType: "numeric",
    refMin: 200.0,
    refMax: 900.0,
    aliases: ["vitamin b12", "b12", "cobalamin"],
  },
  {
    id: "calcium_serum",
    name: "Calcium, Serum",
    shortName: "Calcium",
    category: "Vitamin & Minerals",
    defaultUnit: "mg/dL",
    allowedUnits: ["mg/dL", "mmol/L"],
    valueType: "numeric",
    refMin: 8.5,
    refMax: 10.5,
    aliases: ["calcium", "serum calcium"],
  },
  {
    id: "folic_acid",
    name: "Folate (Folic Acid), Serum",
    shortName: "Folate",
    category: "Vitamin & Minerals",
    defaultUnit: "ng/mL",
    allowedUnits: ["ng/mL", "nmol/L"],
    valueType: "numeric",
    refMin: 4.0,
    refMax: 20.0,
    aliases: ["folic acid", "folate"],
  },
  {
    id: "zinc_serum",
    name: "Zinc, Serum",
    shortName: "Zinc",
    category: "Vitamin & Minerals",
    defaultUnit: "ug/dL",
    allowedUnits: ["ug/dL", "umol/L"],
    valueType: "numeric",
    refMin: 70.0,
    refMax: 120.0,
  },

  // ─────────────────────────────────────────────────────────────
  // 14. FEVER PROFILE
  // ─────────────────────────────────────────────────────────────
  {
    id: "widal_test",
    name: "Widal Test (Typhoid Serology)",
    shortName: "Widal",
    category: "Fever Profile",
    defaultUnit: "Titre",
    allowedUnits: ["Titre", "Qualitative"],
    valueType: "enum",
    qualitativeOptions: ["Negative (TO/TH < 1:80)", "Positive TO ≥ 1:160", "Positive TH ≥ 1:160", "Positive TO & TH ≥ 1:160"],
    aliases: ["widal", "typhoid"],
  },
  {
    id: "malaria_antigen",
    name: "Malaria Antigen (Pf / Pv Rapid Card)",
    shortName: "Malaria Ag",
    category: "Fever Profile",
    defaultUnit: "--",
    allowedUnits: ["--"],
    valueType: "enum",
    qualitativeOptions: ["Negative", "P. falciparum (Pf) Positive", "P. vivax (Pv) Positive", "Both Pf & Pv Positive"],
    aliases: ["malaria", "mp"],
  },
  {
    id: "dengue_ns1",
    name: "Dengue NS1 Antigen",
    shortName: "Dengue NS1",
    category: "Fever Profile",
    defaultUnit: "--",
    allowedUnits: ["--"],
    valueType: "qualitative",
    qualitativeOptions: ["Negative", "Positive"],
    aliases: ["dengue", "ns1"],
  },
  {
    id: "dengue_antibodies",
    name: "Dengue IgM & IgG Antibodies",
    shortName: "Dengue Serology",
    category: "Fever Profile",
    defaultUnit: "--",
    allowedUnits: ["--"],
    valueType: "enum",
    qualitativeOptions: ["Both IgM & IgG Negative", "IgM Positive (Primary Infection)", "IgG Positive (Past/Secondary Infection)", "Both IgM & IgG Positive"],
  },
  {
    id: "crp_fever",
    name: "C-Reactive Protein (CRP), Quantitative",
    shortName: "CRP",
    category: "Fever Profile",
    defaultUnit: "mg/L",
    allowedUnits: ["mg/L", "mg/dL"],
    valueType: "numeric",
    refMin: 0.0,
    refMax: 6.0,
    aliases: ["crp", "c reactive protein"],
  },

  // ─────────────────────────────────────────────────────────────
  // 15. IRON PROFILE
  // ─────────────────────────────────────────────────────────────
  {
    id: "serum_iron",
    name: "Serum Iron",
    shortName: "Iron",
    category: "Iron Profile",
    defaultUnit: "ug/dL",
    allowedUnits: ["ug/dL", "umol/L"],
    valueType: "numeric",
    refMin: 60,
    refMax: 170,
    aliases: ["iron", "serum iron"],
  },
  {
    id: "tibc",
    name: "Total Iron Binding Capacity (TIBC)",
    shortName: "TIBC",
    category: "Iron Profile",
    defaultUnit: "ug/dL",
    allowedUnits: ["ug/dL", "umol/L"],
    valueType: "numeric",
    refMin: 240,
    refMax: 450,
    aliases: ["tibc"],
  },
  {
    id: "transferrin_sat",
    name: "Transferrin Saturation (TSAT)",
    shortName: "TSAT",
    category: "Iron Profile",
    defaultUnit: "%",
    allowedUnits: ["%"],
    valueType: "numeric",
    refMin: 20.0,
    refMax: 50.0,
    aliases: ["transferrin saturation", "tsat"],
  },
  {
    id: "ferritin_serum",
    name: "Ferritin, Serum",
    shortName: "Ferritin",
    category: "Iron Profile",
    defaultUnit: "ng/mL",
    allowedUnits: ["ng/mL", "ug/L"],
    valueType: "numeric",
    refMin: 30.0,
    refMax: 400.0,
    aliases: ["ferritin"],
  },

  // ─────────────────────────────────────────────────────────────
  // 16. PULMONARY FUNCTION TESTS (PFT)
  // ─────────────────────────────────────────────────────────────
  {
    id: "fev1",
    name: "FEV1 (Forced Expiratory Volume in 1s)",
    shortName: "FEV1",
    category: "Pulmonary Function Tests",
    defaultUnit: "L",
    allowedUnits: ["L", "% pred"],
    valueType: "numeric",
    refMin: 2.5,
    refMax: 4.5,
  },
  {
    id: "fvc",
    name: "FVC (Forced Vital Capacity)",
    shortName: "FVC",
    category: "Pulmonary Function Tests",
    defaultUnit: "L",
    allowedUnits: ["L", "% pred"],
    valueType: "numeric",
    refMin: 3.0,
    refMax: 5.5,
  },
  {
    id: "fev1_fvc_ratio",
    name: "FEV1 / FVC Ratio",
    shortName: "FEV1/FVC",
    category: "Pulmonary Function Tests",
    defaultUnit: "%",
    allowedUnits: ["%", "Ratio"],
    valueType: "numeric",
    refMin: 70.0,
    refMax: 85.0,
  },
  {
    id: "pef",
    name: "Peak Expiratory Flow (PEF)",
    shortName: "PEF",
    category: "Pulmonary Function Tests",
    defaultUnit: "L/min",
    allowedUnits: ["L/min"],
    valueType: "numeric",
    refMin: 400,
    refMax: 650,
  },

  // ─────────────────────────────────────────────────────────────
  // 17. CARDIAC & INFLAMMATORY PROFILE
  // ─────────────────────────────────────────────────────────────
  {
    id: "hscrp",
    name: "High Sensitivity CRP (hs-CRP)",
    shortName: "hs-CRP",
    category: "Cardiac & Inflammatory Profile",
    defaultUnit: "mg/L",
    allowedUnits: ["mg/L"],
    valueType: "numeric",
    refMin: 0.0,
    refMax: 1.0,
    aliases: ["hscrp", "hs-crp"],
  },
  {
    id: "troponin_i",
    name: "Troponin I (High Sensitivity)",
    shortName: "Troponin I",
    category: "Cardiac & Inflammatory Profile",
    defaultUnit: "ng/mL",
    allowedUnits: ["ng/mL", "pg/mL"],
    valueType: "numeric",
    refMin: 0.0,
    refMax: 0.04,
    aliases: ["troponin", "trop i"],
  },
  {
    id: "ck_mb",
    name: "Creatine Kinase-MB (CK-MB)",
    shortName: "CK-MB",
    category: "Cardiac & Inflammatory Profile",
    defaultUnit: "ng/mL",
    allowedUnits: ["ng/mL", "U/L"],
    valueType: "numeric",
    refMin: 0.0,
    refMax: 5.0,
  },
  {
    id: "nt_probnp",
    name: "NT-proBNP (N-terminal pro B-type Natriuretic Peptide)",
    shortName: "NT-proBNP",
    category: "Cardiac & Inflammatory Profile",
    defaultUnit: "pg/mL",
    allowedUnits: ["pg/mL", "pmol/L"],
    valueType: "numeric",
    refMin: 0,
    refMax: 125,
    aliases: ["bnp", "nt probnp"],
  },
];
